In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("update_data.csv",sep=",")
df.head(10)

,Searched Email,Kode Identitas,Nama Keluarga/Bangunan/Usaha,Alamat Prelist,Nomor Urut Bangunan / IDSBR,NIB,Email,Skala Usaha / Jenis Prelist,Jumlah Usaha,Kode Pos,Perubahan SLS,IDSBR UMKM SLS Sama,Status,Mode,Petugas Saat Ini,Keterangan,sumber data,nama_kec,koseka,is_prioritas
0,adityahangau@gmail.com,7103090014000100 - DTSEN - 45,DANIEL NANGKODA / JOLFINA MALENDES,SANTIAGO,-,-,-,Keluarga,-,-,-,-,open,CAPI,adityahangau@gmail.comPencacah,-,DTSEN,(090) TAHUNA,Yetty,Ya
1,adityahangau@gmail.com,7103090014000100 - UMK - 1,JUAL MINUMAN POP ICE <KESYA LAHOPANG >,RT 04 KELURAHAN SANTIAGO,12263541,-,-,UMK,-,-,-,-,open,CAPI,adityahangau@gmail.comPencacah,-,UMK,(090) TAHUNA,Yetty,Ya
2,adityahangau@gmail.com,7103090014000100 - DTSEN - 26,MEKEL BALANDATU / YESSY CHLARA MAKITALENTU,KELURAHAN SANTIAGO,-,-,-,Keluarga,-,-,-,-,open,CAPI,adityahangau@gmail.comPencacah,-,DTSEN,(090) TAHUNA,Yetty,Ya
3,adityahangau@gmail.com,7103090014000100 - DTSEN - 21,SIFRIT BAWOEL / JEAN ENJELIN LAUMBURE,KELURAHAN SANTIAGO,-,-,-,Keluarga,-,-,-,-,open,CAPI,adityahangau@gmail.comPencacah,-,DTSEN,(090) TAHUNA,Yetty,Ya
4,adityahangau@gmail.com,7103090014000100 - DTSEN - 6,MARJENS JERMIAS / NOPRIATI PAULENTINE BOHAM,KELURAHAN SANTIAGO,-,-,-,Keluarga,-,-,-,-,open,CAPI,adityahangau@gmail.comPencacah,-,DTSEN,(090) TAHUNA,Yetty,Ya
5,adityahangau@gmail.com,7103090014000100 - DTSEN - 5,JUNICE LOAHE / DEMETRIO SAKAWARI,KELURAHAN SANTIAGO,-,-,-,Keluarga,-,-,-,-,open,CAPI,adityahangau@gmail.comPencacah,-,DTSEN,(090) TAHUNA,Yetty,Ya
6,adityahangau@gmail.com,7103090014000100 - DTSEN - 41,HASNA BALANDATU,KELURAHAN SANTIAGO,-,-,-,Keluarga,-,-,-,-,open,CAPI,adityahangau@gmail.comPencacah,-,DTSEN,(090) TAHUNA,Yetty,Ya
7,adityahangau@gmail.com,7103090014000100 - DTSEN - 17,MILKA KAKUHESE,KELURAHAN SANTIAGO,-,-,-,Keluarga,-,-,-,-,open,CAPI,adityahangau@gmail.comPencacah,-,DTSEN,(090) TAHUNA,Yetty,Ya
8,adityahangau@gmail.com,7103090014000100 - DTSEN - 2,RAMLI SALAWATI / HILDA TAMALAWE,KELURAHAN SANTIAGO,15744185,-,-,Keluarga,-,-,-,-,open,CAPI,adityahangau@gmail.comPencacah,-,DTSEN,(090) TAHUNA,Yetty,Ya
9,adityahangau@gmail.com,7103090014000100 - DTSEN - 39,YOPLIN KATIANDAGHO / SAMSON NANGKODA,KELURAHAN SANTIAGO,-,-,-,Keluarga,-,-,-,-,open,CAPI,adityahangau@gmail.comPencacah,-,DTSEN,(090) TAHUNA,Yetty,Ya

In [ ]:
df['sumber data'].unique()

In [7]:
banyak_sumber = df['sumber data'].unique()
len(banyak_sumber)

588

In [3]:
kode = df['Kode Identitas'].astype(str).str.ljust(16, 'X')

df['kab']     = kode.str[:4]
df['kec']     = kode.str[:7]
df['desa']    = kode.str[:10]
df['sls']     = kode.str[:14]
df['sub_sls'] = kode.str[:16]

df[['Kode Identitas', 'kab', 'kec', 'desa', 'sls', 'sub_sls']].head()

,Kode Identitas,kab,kec,desa,sls,sub_sls
0,7103090014000100 - DTSEN - 45,7103,7103090,7103090014,71030900140001,7103090014000100
1,7103090014000100 - UMK - 1,7103,7103090,7103090014,71030900140001,7103090014000100
2,7103090014000100 - DTSEN - 26,7103,7103090,7103090014,71030900140001,7103090014000100
3,7103090014000100 - DTSEN - 21,7103,7103090,7103090014,71030900140001,7103090014000100
4,7103090014000100 - DTSEN - 6,7103,7103090,7103090014,71030900140001,7103090014000100

In [5]:
levels = ['kab', 'kec', 'desa', 'sls', 'sub_sls']

tabulasi = {}
for lvl in levels:
    tab = (
        df.groupby([lvl, 'Skala Usaha / Jenis Prelist'])
        .size()
        .unstack(fill_value=0)
    )
    tab['Total'] = tab.sum(axis=1)
    tabulasi[lvl] = tab

# Tampilkan semua tabulasi
for lvl, tab in tabulasi.items():
    print(f"\n{'='*60}")
    print(f"Tabulasi berdasarkan: {lvl.upper()}")
    print('='*60)
    display(tab)

============================================================
Tabulasi berdasarkan: KAB
============================================================

Skala Usaha / Jenis Prelist,Keluarga,UB,UM,UMK,UMKM Bangunan Lain,UMKM/Dummy,UMKM/Keluarga,Total
kab,,,,,,,,
7103,40121,21,53,5860,1567,16,1987,49625
WILM,1,0,0,0,0,0,0,1

============================================================
Tabulasi berdasarkan: KEC
============================================================

Skala Usaha / Jenis Prelist,Keluarga,UB,UM,UMK,UMKM Bangunan Lain,UMKM/Dummy,UMKM/Keluarga,Total
kec,,,,,,,,
7103040,2858,0,2,506,99,0,260,3725
7103041,1103,0,0,131,60,0,41,1335
7103050,4262,3,2,499,203,2,238,5209
7103060,1996,0,1,440,86,0,148,2671
7103061,804,0,0,94,57,1,64,1020
7103062,692,0,0,75,56,0,49,872
7103070,3244,0,0,332,181,0,179,3936
7103080,4272,0,4,597,130,4,194,5201
7103090,5509,11,28,1331,115,0,159,7153
7103091,3890,5,8,552,87,0,219,4761
7103092,1992,1,0,168,57,0,57,2275
7103100,6129,1,5,816,265,0,256,7472
7103101,864,0,1,34,50,6,26,981
7103102,398,0,0,41,56,0,21,516
7103110,2108,0,2,244,65,3,76,2498
WILMAR,1,0,0,0,0,0,0,1

============================================================
Tabulasi berdasarkan: DESA
============================================================

Skala Usaha / Jenis Prelist,Keluarga,UB,UM,UMK,UMKM Bangunan Lain,UMKM/Dummy,UMKM/Keluarga,Total
desa,,,,,,,,
7103040005,124,0,0,3,13,0,0,140
7103040006,253,0,0,12,3,0,12,280
7103040007,288,0,0,43,2,0,5,338
7103040008,132,0,0,27,11,0,30,200
7103040009,234,0,0,18,5,0,4,261
...,...,...,...,...,...,...,...,...
7103110005,285,0,0,13,15,1,3,317
7103110006,298,0,1,62,13,0,9,383
7103110007,80,0,0,6,0,1,8,95
7103110008,146,0,0,13,4,0,8,171
WILMAR JAC,1,0,0,0,0,0,0,1

============================================================
Tabulasi berdasarkan: SLS
============================================================

Skala Usaha / Jenis Prelist,Keluarga,UB,UM,UMK,UMKM Bangunan Lain,UMKM/Dummy,UMKM/Keluarga,Total
sls,,,,,,,,
71030400050001,18,0,0,0,4,0,0,22
71030400050002,55,0,0,2,7,0,0,64
71030400050003,34,0,0,1,1,0,0,36
71030400050004,17,0,0,0,1,0,0,18
71030400060001,86,0,0,11,3,0,7,107
...,...,...,...,...,...,...,...,...
71031100080002,34,0,0,4,1,0,2,41
71031100080003,42,0,0,2,0,0,1,45
71031100080004,38,0,0,1,0,0,3,42
71031100081001,0,0,0,1,0,0,0,1
WILMAR JACOBXX,1,0,0,0,0,0,0,1

============================================================
Tabulasi berdasarkan: SUB_SLS
============================================================

Skala Usaha / Jenis Prelist,Keluarga,UB,UM,UMK,UMKM Bangunan Lain,UMKM/Dummy,UMKM/Keluarga,Total
sub_sls,,,,,,,,
7103040005000100,18,0,0,0,4,0,0,22
7103040005000200,55,0,0,2,7,0,0,64
7103040005000300,34,0,0,1,1,0,0,36
7103040005000400,17,0,0,0,1,0,0,18
7103040006000100,86,0,0,11,3,0,7,107
...,...,...,...,...,...,...,...,...
7103110008000200,34,0,0,4,1,0,2,41
7103110008000300,42,0,0,2,0,0,1,45
7103110008000400,38,0,0,1,0,0,3,42
7103110008100100,0,0,0,1,0,0,0,1
WILMAR JACOBXXXX,1,0,0,0,0,0,0,1